/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard'],
  rules: {
    'custom-property-empty-line-before': null,
    'rule-empty-line-before': null,
    'at-rule-empty-line-before': null,
    'declaration-empty-line-before': null,
    'media-feature-range-notation': null,
    'color-function-alias-notation': null,
    'value-keyword-case': null,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global', 'local'],
      },
    ],
    'no-duplicate-selectors': null,
    'function-no-unknown': true,
    'at-rule-no-unknown': true,
    'block-no-empty': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-redundant-longhand-properties': true,
    'shorthand-property-no-redundant-values': true,
    'function-url-quotes': 'always',
    'color-hex-length': 'short',
    'color-named': 'never',
    'comment-no-empty': true,
    'font-family-name-quotes': 'always-unless-keyword',
    'property-no-vendor-prefix': true,
    'value-no-vendor-prefix': true,
    'selector-no-vendor-prefix': true,
    'no-descending-specificity': null,
    'keyframe-selector-notation': 'percentage',
    'selector-class-pattern': null,
    'keyframes-name-pattern': null,
    'font-weight-notation': null,
    'color-function-notation': null,
    'alpha-value-notation': 'number',
  },
}
