/* generated by unplugin-react-components */
export {}
declare global{
	const Icon: typeof import('./src/icons/index')['default']
	const AppLayout: typeof import('./src/layout/index')['default']
	const LoginView: typeof import('./src/views/login/index')['default']
	const SystemView: typeof import('./src/views/system/index')['default']
	const Collapse: typeof import('./src/layout/components/LayoutSider/Collapse')['default']
	const LayoutSider: typeof import('./src/layout/components/LayoutSider/index')['default']
	const Logo: typeof import('./src/layout/components/LayoutSider/Logo')['default']
	const LayoutMenu: typeof import('./src/layout/components/LayoutSider/Menu')['default']
	const SystemRoleView: typeof import('./src/views/system/role/index')['default']
	const SystemUserView: typeof import('./src/views/system/user/index')['default']
	const Icon: typeof import('/src/icons')['default']
}